// Set-up for leaf 1.4.5's end-to-end tests: a household made through the API as a person would
// (sign-up, one change set, an invite accepted), and today's plan generated by the real worker.
// Sessions are kept as Playwright storage states, so no test signs in through the rate-limited form.
import { randomUUID } from "node:crypto";
import { expect, type APIRequestContext, type Browser } from "@playwright/test";

export const BASE_URL = `http://localhost:${process.env.PLAYWRIGHT_PORT ?? "3142"}`;
export const PHONE = { width: 390, height: 844 } as const;
export const DESKTOP = { width: 1280, height: 900 } as const;

export interface World {
  run: string;
  householdId: string;
  adminUserId: string;
  adminState: string;
  memberState: string;
  members: { omar: string; sara: string; layla: string; zayd: string };
  /** Today's shared meal that everyone attends (the one reviewed), and its dish. */
  meal: { id: string; dishId: string; dishName: string; slotLabel: string };
  today: string;
}

export function today(): string {
  return new Date().toISOString().slice(0, 10);
}

async function ok(res: Awaited<ReturnType<APIRequestContext["post"]>>, what: string) {
  if (!res.ok()) throw new Error(`${what}: ${String(res.status())} ${await res.text()}`);
  return (await res.json()) as Record<string, unknown>;
}

/** Waits for a job to succeed (the worker runs it). */
export async function waitForJob(request: APIRequestContext, jobId: string, timeoutMs = 120_000) {
  await expect
    .poll(
      async () => {
        const j = (await (await request.get(`/api/v1/jobs/${jobId}`)).json()) as { status: string };
        if (j.status === "failed") throw new Error(`job ${jobId} failed`);
        return j.status;
      },
      { timeout: timeoutMs, intervals: [500, 1000, 2000] },
    )
    .toBe("succeeded");
}

/**
 * The household: admin Sara (targeted), Omar (targeted), Layla 18 and Zayd 10 (untargeted); Layla
 * has a member login; the household lets members review for younger siblings. Today is planned.
 */
export async function createWorld(browser: Browser, tag: string): Promise<World> {
  const run = `${tag}-${randomUUID().slice(0, 8)}`;
  const admin = await browser.newContext({ baseURL: BASE_URL });
  const a = admin.request;
  const signup = await ok(
    await a.post("/api/v1/signup", {
      data: {
        email: `sara-${run}@example.com`,
        password: "sara-password-1",
        name: "Sara",
        householdName: `Khalifa City home ${run}`,
      },
    }),
    "signup",
  );
  const householdId = signup.householdId as string;
  const adminUserId = (signup.user as { id: string }).id;
  const members = { omar: randomUUID(), sara: randomUUID(), layla: randomUUID(), zayd: randomUUID() };
  const year = new Date().getUTCFullYear();
  await ok(
    await a.post("/api/v1/change-sets", {
      data: {
        summary: "Set up the family",
        ops: [
          { kind: "member.create", payload: { id: members.omar, displayName: "Omar", color: "sea", isTargeted: true, birthYear: year - 41, sex: "male" } },
          { kind: "member.create", payload: { id: members.sara, displayName: "Sara", color: "tomato", isTargeted: true, birthYear: year - 39, sex: "female" } },
          { kind: "member.create", payload: { id: members.layla, displayName: "Layla", color: "basil", isTargeted: false, birthYear: year - 18, sex: "female", appetite: "large" } },
          { kind: "member.create", payload: { id: members.zayd, displayName: "Zayd", color: "saffron", isTargeted: false, birthYear: year - 10, sex: "male", appetite: "medium" } },
          { kind: "target.set", payload: { memberId: members.omar, kind: "default", profile: { kcal: 2150, proteinG: 180, carbsG: 200, fatG: 70 } } },
          { kind: "target.set", payload: { memberId: members.sara, kind: "default", profile: { kcal: 1655, proteinG: 130, carbsG: 160, fatG: 55 } } },
          { kind: "household.update", payload: { membersReviewForSiblings: true } },
        ],
      },
    }),
    "family",
  );
  const invite = await ok(
    await a.post("/api/v1/invites", { data: { role: "member", memberId: members.layla } }),
    "invite",
  );
  const member = await browser.newContext({ baseURL: BASE_URL });
  await ok(
    await member.request.post("/api/v1/invites/accept", {
      data: {
        code: invite.code,
        signup: { email: `layla-${run}@example.com`, password: "layla-password-1", name: "Layla" },
      },
    }),
    "accept",
  );
  const date = today();
  const job = await ok(await a.post("/api/v1/plans/generate", { data: { dates: [date] } }), "generate");
  await waitForJob(a, job.jobId as string);
  const plans = (await (await a.get(`/api/v1/plans?from=${date}&to=${date}`)).json()) as {
    days: { meals: { id: string; dishId: string; dishName: string; slotLabel: string; kind: string; attendees: string[] }[] }[];
  };
  const meals = plans.days[0]?.meals ?? [];
  const meal =
    meals.find((m) => m.kind === "shared" && m.attendees.includes(members.layla) && m.attendees.includes(members.zayd) && m.attendees.includes(members.omar)) ??
    meals.find((m) => m.attendees.includes(members.layla));
  if (meal === undefined) throw new Error(`no meal for Layla today (${String(meals.length)} meals)`);
  const world: World = {
    run,
    householdId,
    adminUserId,
    adminState: JSON.stringify(await admin.storageState()),
    memberState: JSON.stringify(await member.storageState()),
    members,
    meal: { id: meal.id, dishId: meal.dishId, dishName: meal.dishName, slotLabel: meal.slotLabel },
    today: date,
  };
  await admin.close();
  await member.close();
  return world;
}

export async function contextFor(
  browser: Browser,
  state: string,
  viewport: { width: number; height: number },
  colorScheme: "light" | "dark" = "light",
) {
  return browser.newContext({
    baseURL: BASE_URL,
    viewport,
    colorScheme,
    storageState: JSON.parse(state) as { cookies: []; origins: [] },
  });
}
