// Facts about the candidate pool that scoring and filtering read repeatedly: core ingredients per
// variant (PLN-9 economy, via the 1.3.2 definition), the main protein ingredient (variety,
// SPEC-Q-9) and the slug → id map for exclusion keys (BLD-8 R-36).
import { coreIngredients } from "../../learning/preferences/index.js";
import type { PlanComponent, PlanDish, PlanVariant } from "./types.js";

export type VariantInfo = {
  dish: PlanDish;
  component: PlanComponent;
  variant: PlanVariant;
  core: readonly string[];
  /** Heaviest raw core ingredient, for a `protein`-role component; null otherwise. */
  mainProtein: string | null;
};

export class Pool {
  readonly dishes = new Map<string, PlanDish>();
  readonly adjusters = new Map<string, PlanDish>();
  private readonly variants = new Map<string, VariantInfo>();
  /** Ingredient slug → id, over every variant in the pool (R-36). */
  readonly idBySlug = new Map<string, string>();
  readonly slugById = new Map<string, string>();

  constructor(dishes: readonly PlanDish[], adjusters: readonly PlanDish[]) {
    for (const d of dishes) this.add(d, false);
    for (const a of adjusters) this.add(a, true);
  }

  /** Adds a dish (for example one generated by PLN-12); a known id is ignored. */
  add(dish: PlanDish, adjuster: boolean): void {
    const target = adjuster ? this.adjusters : this.dishes;
    if (this.dishes.has(dish.id) || this.adjusters.has(dish.id)) return;
    target.set(dish.id, dish);
    for (const component of dish.components)
      for (const variant of component.variants) {
        for (const i of variant.ingredients) {
          this.idBySlug.set(i.slug, i.id);
          this.slugById.set(i.id, i.slug);
        }
        const core = coreIngredients(
          variant.ingredients.map((i) => ({
            ingredientId: i.id,
            slug: i.slug,
            category: i.category,
          })),
        );
        this.variants.set(variant.id, {
          dish,
          component,
          variant,
          core,
          mainProtein: component.role === "protein" ? heaviest(variant, core) : null,
        });
      }
  }

  dish(id: string): PlanDish | undefined {
    return this.dishes.get(id) ?? this.adjusters.get(id);
  }

  variant(id: string): VariantInfo | undefined {
    return this.variants.get(id);
  }

  /** Core ingredients of the given variants, deduplicated, in first-seen order. */
  coreOf(variantIds: Iterable<string>): string[] {
    const out = new Set<string>();
    for (const id of variantIds) for (const i of this.variants.get(id)?.core ?? []) out.add(i);
    return [...out];
  }

  /** The main protein of a dish as served: the first protein component's served variant. */
  mainProteinOf(dish: PlanDish, variantIds: ReadonlySet<string>): string | null {
    for (const c of dish.components) {
      if (c.role !== "protein") continue;
      const served = c.variants.find((v) => variantIds.has(v.id));
      if (served !== undefined) return this.variants.get(served.id)?.mainProtein ?? null;
    }
    return null;
  }
}

function heaviest(variant: PlanVariant, core: readonly string[]): string | null {
  const grams = new Map<string, number>();
  for (const row of variant.input.ingredients)
    if (core.includes(row.ingredientId) && !row.isAbsorbedOil)
      grams.set(row.ingredientId, (grams.get(row.ingredientId) ?? 0) + row.rawG);
  let best: string | null = null;
  let bestG = -1;
  for (const [id, g] of grams)
    if (g > bestG) {
      best = id;
      bestG = g;
    }
  return best;
}

/** Ids of the variants served on a set of plates (items and adjusters). */
export function servedVariantIds(
  plates: ReadonlyArray<{ solution: { items: ReadonlyArray<{ variantId: string }> } }>,
): Set<string> {
  const ids = new Set<string>();
  for (const p of plates) for (const item of p.solution.items) ids.add(item.variantId);
  return ids;
}
