// Every table and column named by 02-domain-model (as amended by BLD-8 R-11, R-12), 13-revision-r2
// and the BLD-8 R-8/R-9 rulings, written from the spec text, independently of src/schema. G1
// introspects a migrated database against this list.

/** Tables the auth library manages (02 §1 session, ADR-4) and 13 §4 names without columns. */
export const SPEC_TABLES_WITHOUT_COLUMN_LIST = ["session", "account", "verification"] as const;

export const SPEC_COLUMNS: Record<string, readonly string[]> = {
  // 02 §1 (R-11: no password_hash), R-9 i
  user: ["id", "email", "name", "created_at", "platform_blocked_at"],
  household: [
    "id",
    "name",
    "locale",
    "timezone",
    "unit_system",
    "country_code",
    "region_note",
    "members_see_plates",
    "agent_may_apply",
    "created_at",
    // R-9 h (R2-ADM-5/6)
    "require_totp_for_admins",
    "kitchen_sees_names",
    "members_review_for_siblings",
    "insight_frequency",
    "default_precision",
    "sat_fat_default_pct",
    // R-9 i (R2-ADM-6/8)
    "deletion_requested_at",
    "deletion_requested_by_user_id",
    "suspended_at",
  ],
  // 02 §1 + 13 R2-ADM-4 status/blocked_reason + R-9 k
  household_user: [
    "household_id",
    "user_id",
    "role",
    "member_id",
    "status",
    "blocked_reason",
    "last_active_at",
  ],
  // 02 §1 + R-9 g
  invite: [
    "id",
    "household_id",
    "code",
    "role",
    "member_id",
    "expires_at",
    "used_at",
    "revoked_at",
    "created_by_user_id",
  ],
  // 13 R2-ADM-8
  platform_operator: ["user_id"],
  support_grant: [
    "id",
    "household_id",
    "operator_user_id",
    "granted_by_user_id",
    "expires_at",
    "revoked_at",
  ],
  // 13 R2-ADM-5 TOTP secret
  two_factor: ["user_id", "secret"],
  // R-9 j
  user_notification_pref: ["user_id", "key", "enabled"],
  // 02 §2 (+ household_id, R-8)
  member: [
    "id",
    "household_id",
    "display_name",
    "color",
    "birth_year",
    "sex",
    "is_targeted",
    "appetite",
    "notes",
    "archived_at",
  ],
  target_profile: [
    "id",
    "household_id",
    "member_id",
    "kind",
    "kcal",
    "protein_g",
    "carbs_g",
    "fat_g",
    "sat_fat_max_g",
    "soluble_fibre_min_g",
    "fibre_min_g",
    "sodium_max_mg",
  ],
  tolerance: ["household_id", "member_id", "protein_g", "carbs_g", "fat_g", "kcal", "mode"],
  slot_type: [
    "id",
    "household_id",
    "key",
    "label",
    "icon", // R-23
    "sort_order",
    "default_time",
    "is_shared",
    "is_packed",
    "reheat_available",
    "is_training_slot",
    "constraints_note",
    "active",
  ],
  member_slot_schedule: ["household_id", "member_id", "slot_type_id", "weekday", "attends"],
  training_schedule: ["household_id", "member_id", "weekday", "session_time", "intensity"],
  day_override: ["household_id", "member_id", "date", "kind", "slot_type_id"],
  meal_distribution: ["household_id", "member_id", "day_kind", "slot_type_id", "share"],
  slot_target_override: [
    "household_id",
    "member_id",
    "day_kind",
    "slot_type_id",
    "kcal",
    "protein_g",
    "carbs_g",
    "fat_g",
  ],
  // R-9 e, f
  portion_bias: ["household_id", "member_id", "component_role", "bias"],
  detail_level: ["household_id", "member_id", "section", "level"],
  // 02 §3 + R-9 b, l
  ingredient: [
    "id",
    "slug",
    "name",
    "aliases",
    "category",
    "kcal",
    "protein_g",
    "carbs_g",
    "fat_g",
    "sat_fat_g",
    "fibre_g",
    "soluble_fibre_g",
    "sugar_g",
    "sodium_mg",
    "density_g_per_ml",
    "unit_weight_g",
    "unit_label",
    "edible_portion",
    "dietary_flags",
    "nutrition_source",
    "nutrition_confidence",
    "locale_availability",
    "created_by_household_id",
    "needs_review",
    "verified_at",
    "verified_by_user_id",
  ],
  preparation_method: ["id", "key", "label", "description", "appeal_tags"],
  // R-12: no coating columns
  method_yield: [
    "method_id",
    "ingredient_category",
    "yield_factor",
    "fat_retention",
    "oil_absorption_g_per_100g_raw",
  ],
  cuisine: ["id", "key", "label", "parent_key"], // R-23: no flag_emoji
  // 02 §4 (+ household_id on children, R-8) + R-9 a, b, d, R-12
  dish: [
    "id",
    "household_id",
    "name",
    "slug",
    "description",
    "cuisine_id",
    "secondary_cuisine_id",
    "slot_keys",
    "flavour_tags",
    "is_packable",
    "served_cold_ok",
    "source",
    "status",
    "ai_generation_id",
    "version",
    "created_at",
    "updated_at",
  ],
  component: [
    "id",
    "household_id",
    "dish_id",
    "name",
    "role",
    "portioning",
    "unit_label",
    "min_serving_g",
    "max_serving_g",
    "default_serving_g",
    "step_g",
    "sort_order",
    "required",
  ],
  variant: [
    "id",
    "household_id",
    "component_id",
    "method_id",
    "label",
    "is_default",
    "steps",
    "cook_time_min",
    "notes",
    "reference_batch_cooked_g",
    "needs_review",
  ],
  variant_ingredient: [
    "household_id",
    "variant_id",
    "ingredient_id",
    "raw_g_per_batch",
    "role_note",
    "is_absorbed_oil",
    "cooking_liquid",
    "yield_override",
  ],
  dish_nutrition_cache: [
    "variant_id",
    "kcal",
    "protein",
    "carbs",
    "fat",
    "sat_fat",
    "fibre",
    "soluble_fibre",
    "sugar",
    "sodium",
    "cooked_yield_g_per_batch",
    "computed_at",
    "engine_version",
  ],
  household_adjuster: ["household_id", "dish_id", "enabled"],
  // 02 §5 + 13 R2-MEAL-2
  plan_day: [
    "id",
    "household_id",
    "date",
    "status",
    "weights_snapshot",
    "generated_at",
    "generator_version",
  ],
  plan_meal: [
    "id",
    "household_id",
    "plan_day_id",
    "slot_type_id",
    "dish_id",
    "dish_version",
    "member_scope",
    "locked",
    "score_breakdown",
    "status",
  ],
  plate: [
    "id",
    "household_id",
    "plan_meal_id",
    "member_id",
    "fit_status",
    "target",
    "actual",
    "deviation",
  ],
  plate_item: [
    "household_id",
    "plate_id",
    "component_id",
    "variant_id",
    "cooked_g",
    "raw_equivalent",
  ],
  cook_batch: [
    "household_id",
    "plan_meal_id",
    "variant_id",
    "total_cooked_g",
    "raw_ingredients",
    "servings",
  ],
  meal_override: ["household_id", "plan_date", "slot_type_id", "kind", "member_ids", "created_by"],
  // 02 §6 + R-9 d
  review: [
    "id",
    "household_id",
    "author_user_id",
    "on_behalf_of_member_id",
    "target_type",
    "target_id",
    "plan_meal_id",
    "rating",
    "tags",
    "comment",
    "parent_review_id",
    "created_at",
    "edited_at",
    "processed_at",
  ],
  review_reaction: ["household_id", "review_id", "user_id", "kind"],
  review_revision: [
    "id",
    "household_id",
    "review_id",
    "rating",
    "tags",
    "comment",
    "replaced_at",
    "edited_by_user_id",
  ],
  preference: [
    "id",
    "household_id",
    "member_id",
    "entity_type",
    "entity_key",
    "score",
    "evidence_weight",
    "source",
    "locked",
    "hard",
    "updated_at",
  ],
  frequency_rule: [
    "household_id",
    "member_id",
    "entity_type",
    "entity_key",
    "min_gap_days",
    "max_per_week",
    "source",
    "locked",
  ],
  exclusion: ["household_id", "member_id", "kind", "key", "reason", "hard"],
  planning_weights: [
    "household_id",
    "macro_precision",
    "appeal",
    "ingredient_economy",
    "variety",
    "fairness",
    "ai_generation",
    "economy_window_days",
    "updated_at",
    "adjusters_enabled",
    "max_variants_per_component",
  ],
  weight_preset: ["household_id", "name", "values", "applies_to_weekdays"],
  // 02 §7
  conversation: ["id", "household_id", "user_id", "title", "created_at", "archived_at"],
  chat_message: ["id", "household_id", "conversation_id", "role", "content", "created_at"],
  proposal: [
    "id",
    "household_id",
    "origin",
    "conversation_id",
    "message_id",
    "kind",
    "payload",
    "rationale",
    "evidence",
    "fingerprint",
    "status",
    "decided_by_user_id",
    "decided_at",
    "decision_note",
    "change_set_id",
    "expires_at",
  ],
  change_set: [
    "id",
    "household_id",
    "actor",
    "actor_user_id",
    "source",
    "summary",
    "forward",
    "inverse",
    "applied_at",
    "undone_at",
    "undone_by_change_set_id",
  ],
  // 02 §8, §9
  kg_node: ["id", "household_id", "type", "key", "label", "props"],
  kg_edge: [
    "id",
    "household_id",
    "src_id",
    "dst_id",
    "type",
    "weight",
    "props",
    "source",
    "updated_at",
  ],
  ai_generation: [
    "id",
    "household_id",
    "purpose",
    "model",
    "request_summary",
    "response_raw",
    "input_tokens",
    "output_tokens",
    "cache_read_tokens",
    "stop_reason",
    "validation_errors",
    "created_at",
  ],
};

/** Columns the rulings removed or replaced; they must not exist. */
export const SPEC_ABSENT_COLUMNS: Record<string, readonly string[]> = {
  user: ["password_hash"], // R-11
  method_yield: ["coating_ingredient_id", "coating_g_per_100g_raw"], // R-12
  variant_ingredient: ["retained"], // R-12 replaces SPEC-Q-4c
  // R-23 (R2-UX-5): no emoji in data
  member: ["emoji_avatar"],
  cuisine: ["flag_emoji"],
  slot_type: ["emoji"],
};

/** Enumerations whose values 02 / 13 fix, as Postgres enum type → values in order. */
export const SPEC_ENUM_VALUES: Record<string, readonly string[]> = {
  household_role: ["admin", "member", "kitchen"],
  household_user_status: ["active", "invited", "blocked"],
  meal_override_kind: ["split_member", "make_individual"],
  cooking_liquid: ["absorbed", "retained"],
  fit_status: ["in_tolerance", "flexible_miss", "infeasible", "untargeted"],
  change_source: ["ui", "agent_apply", "proposal_accept", "learning"],
  change_actor: ["user", "agent", "system"],
  proposal_status: ["pending", "accepted", "rejected", "expired", "superseded"],
  exclusion_reason: ["allergy", "religious", "dislike", "medical", "other"],
  tolerance_mode: ["strict", "flexible"],
};

/** Uniqueness the spec states (02), as table → column sets that must be unique or a primary key. */
export const SPEC_UNIQUE: readonly [string, readonly string[]][] = [
  ["user", ["email"]],
  ["household_user", ["household_id", "user_id"]],
  ["invite", ["code"]],
  ["target_profile", ["member_id", "kind"]],
  ["tolerance", ["member_id"]],
  ["ingredient", ["slug"]],
  ["preparation_method", ["key"]],
  ["cuisine", ["key"]],
  ["dish_nutrition_cache", ["variant_id"]],
  ["plan_day", ["household_id", "date"]],
  ["preference", ["household_id", "member_id", "entity_type", "entity_key", "source"]],
  ["planning_weights", ["household_id"]],
  ["kg_node", ["household_id", "type", "key"]],
];

/** 02 §8: kg_edge indexes on (src_id, type) and (dst_id, type). */
export const SPEC_INDEXES: readonly [string, readonly string[]][] = [
  ["kg_edge", ["src_id", "type"]],
  ["kg_edge", ["dst_id", "type"]],
];
